[package]
name = "crm_query"
version = "0.1.0"
authors = ["Tobias de Bruijn <github@thedutchmc.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.125"
serde_json = "1.0.64"
serde_yaml = "0.8.17"
reqwest = "0.11.3"
espocrm-rs = "0.2.1"
actix-web = "3.3.2"
actix-cors = "0.5.4"
envy = "0.4.2"
log = "0.4.14"

[dependencies.tokio]
version = "1.8.2"
features = ["full"]

[dependencies.log4rs]
version = "1.0.0"
features = ["console_appender"]